# -*- coding: utf-8 -*-
"""ARIMA_LSTM_with_return.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16HBCrmUKcvCXnqAhj9wmPya5TCP3OUjI
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math
import os
from os.path import join as opj
import random
from tqdm import tqdm
import scipy.stats as stats
import pylab as pl
from pmdarima import ARIMA, auto_arima
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import warnings

from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, LSTM, Activation
from tensorflow.keras import backend as K
from tensorflow.keras.saving import get_custom_objects
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.regularizers import l1_l2

warnings.simplefilter("ignore")

# use google drive
from google.colab import drive
drive.mount('/content/drive')

"""# Create Residual with ARIMA (for predicting)"""

def rolling_corr(item1, item2, stock_price_df, window=100):
    df_pair = pd.concat([stock_price_df[item1], stock_price_df[item2]], axis=1)
    df_pair.columns = [item1, item2]
    df_corr = df_pair[item1].rolling(window=window).corr(df_pair[item2])
    return df_corr

def get_data(st_date, chunk_size, num_chunk, portfolio, root_path) -> tuple[pd.DataFrame, pd.DataFrame]:
  df = pd.read_csv(opj(root_path, '20industries_ETF_prc_UNSTACKED.csv'))
  pd.to_datetime(df['datadate'], format='%Y-%m-%d')
  df = df.set_index(pd.DatetimeIndex(df['datadate']))

  df = df[df.index >= pd.to_datetime(st_date)]

  num_asset = len(portfolio)

  data_matrix = []
  dict_ret2 = {}
  dict_corr = {}

  for i, asset in tqdm(enumerate(portfolio), total=len(portfolio)):

    # calculate square of the return rate
    ret2_series = df[asset].astype(float).pct_change(chunk_size - 1).shift(-chunk_size+1).fillna(0) ** 2
    ret2_strided = list(ret2_series[[chunk_size*k for k in range(num_chunk)]])
    dict_ret2[str(i)] = ret2_strided

    # calculate history correlation
    for j in range(num_asset-1-i):
      a = portfolio[i]
      b = portfolio[num_asset-1-j]
      corr_series = rolling_corr(a,b, df, chunk_size)[chunk_size - 1:]
      corr_strided = list(corr_series[[chunk_size*k for k in range(num_chunk)]])
      data_matrix.append(corr_strided)

  for i in range(len(data_matrix)):
      dict_corr[str(i)] = data_matrix[i]

  data_corr = pd.DataFrame(dict_corr)
  data_ret2 = pd.DataFrame(dict_ret2)
  data_corr = data_corr.transpose()
  data_ret2 = data_ret2.transpose()
  return data_corr, data_ret2

def getArima(dataset) -> tuple[list, list]:

  orders = [(1,1,0), (0,1,1), (1,1,1), (2,1,1), (2,1,0)]
  models = [ARIMA(order=order, suppress_warnings=False) for order in orders]

  c=0
  residuals = []
  preds = []
  for s in tqdm(np.array(dataset)):
      c+=1
      best_model = auto_arima(s, seasonal=False)

      in_sample_pred = list(best_model.predict_in_sample())
      #pad the first time step of predictions with the average of the prediction values
      #so as to match the length of the s[i] data
      # predictions = [np.mean(predictions)] + predictions

      pred = list(best_model.predict(1))

      res = pd.Series(np.array(s) - np.array(in_sample_pred))
      residuals.append(np.array(res))
      preds.append(pred)

  residuals = pd.DataFrame(residuals)
  return preds, residuals

"""# APPLY LSTM MODEL (for predicting)"""

#define custom activation
class Double_Tanh(Activation):
    def __init__(self, activation, **kwargs):
        super(Double_Tanh, self).__init__(activation, **kwargs)
        self.__name__ = 'double_tanh'

def double_tanh(x):
    # TODO: figure out why *2
    return (K.tanh(x) * 2)
    # return K.tanh(x)

def getLSTM(dataset, num_chunk, root_path):
  get_custom_objects().update({'double_tanh':Double_Tanh(double_tanh)})
  model = load_model(opj(root_path, "model", "epoch247.h5"))

  X = np.asarray(dataset).reshape(dataset.shape[0],num_chunk,1)
  pred = model.predict(X)
  return pred

def assemble(pred_arima, pred_lstm):
  pred = np.array(pred_arima) + np.array(pred_lstm) / 2
  pred = pred.squeeze()
  pred = np.maximum(np.minimum(pred, 1), -1)
  return pred

def ARIMA_LSTM(start_date, chunk_size, num_chunk, portfolio, root_path):

  num_asset = len(portfolio)

  data_df, data_ret2 = get_data(start_date, chunk_size, num_chunk, portfolio, root_path)

  nan_values = data_df.isnull().values.any()
  nan_values = data_ret2.isnull().values.any()
  corr_pred_ARIMA, corr_residuals = getArima(data_df)
  ret2_pred_ARIMA, ret2_residuals = getArima(data_ret2)

  corr_pred_LSTM = getLSTM(corr_residuals, num_chunk, root_path)
  ret2_pred_LSTM = getLSTM(ret2_residuals, num_chunk, root_path)

  corr_pred = assemble(corr_pred_ARIMA, corr_pred_LSTM)
  ret2_pred = assemble(ret2_pred_ARIMA, ret2_pred_LSTM)

  cov_mat = np.zeros((num_asset, num_asset), dtype=float)

  # fill with correlation
  start = 0
  for i in range(num_asset):
    end = start + num_asset - i - 1
    cov_mat[i,i+1:] = corr_pred[start:end]
    start = end
    item = portfolio[i]
  cov_mat = cov_mat + cov_mat.T

  # correlation with itself is 1
  np.fill_diagonal(cov_mat, 1)

  # Cov(X,Y) = rho(x,y) * sigma(x) * sigma(y)
  for i in range(num_asset):
    # assume the average of the returns in the short term is 0, then Cov(X,X) = sigma^2(x) = E(x^2)
    cov_mat[:, i] *= np.sqrt(ret2_pred[i])
    cov_mat[i] *= np.sqrt(ret2_pred[i])

  return cov_mat
